SELECT 
    TO_CHAR(A.ACTIVITY_DATE, 'YYYY-MM-DD') AS DAY,
    COUNT(DISTINCT USER_ID) AS ACTIVE_USERS
FROM ACTIVITY A
WHERE 
    TO_DATE('2019-07-27', 'YYYY-MM-DD') - A.ACTIVITY_DATE >= 0 AND
    TO_DATE('2019-07-27', 'YYYY-MM-DD') - A.ACTIVITY_DATE <= 29
GROUP BY A.ACTIVITY_DATE
HAVING COUNT(DISTINCT USER_ID) > 0
ORDER BY A.ACTIVITY_DATE;